#!/usr/bin/env Rscript

# Maintainer information.
maintainer.info <- c("Firstname Lastname, firstname.lastname at email dot com")

# CRAN mirror to use; full list: https://cran.r-project.org/mirrors.html
# This can be left as it is -- automatic redirection to servers worldwide,
# currently sponsored by Posit.
cranrepo.url <- "https://cloud.r-project.org"

# Bioconductor url. This can be left as it is.
bioc.url <- "https://bioconductor.org/packages/"

# BioConductor version.
# Version 3.22 is for R 4.5
# Version 3.23 is for R 4.6
bioc.version <- "3.23"
